service = {
    'gc': 'TradingView',
    'lb': 'Mailru Group',
    'az': 'CityBase',
    'wl': 'YouGotaGift',
    'cn': 'Fiverr',
    'km': 'Rozetka',
    'lt': 'BitClout',
    'jf': 'Likee',
    'sf': 'SneakersnStuff',
    'tj': 'dbrUA',
    'full': 'Полная',
    'ce': 'mosru',
    'kf': 'Weibo',
    'ip': 'Burger King',
    'qd': 'Taobao',
    'yn': 'Allegro',
    'af': 'GalaxyWin',
    'ou': 'Gabi',
    'tt': 'Ziglu',
    'ff': 'AVON',
    'qo': 'Moneylion',
    'dn': 'Paxful',
    'pr': 'Trendyol',
    'ly': 'Olacabs',
    'vf': 'Q12 Trivia',
    'zm': 'OfferUp',
    'jh': 'PingPong',
    'fe': 'CliQQ',
    'rt': 'hily',
    'wc': 'Craigslist',
    'sw': 'NCsoft',
    'vv': 'Seosprint',
    'kn': 'Verse',
    'ug': 'Fiqsy',
    'rx': 'Sheerid',
    'cw': 'PaddyPower',
    'jl': 'Hopi',
    'qh': 'Oriflame',
    'mu': 'MyMusicTaste',
    'vw': 'CoinField',
    'kl': 'kolesa.kz',
    'li': 'Baidu',
    'bf': 'Keybase',
    'kb': 'kufar',
    'll': '888casino',
    'zr': 'Papara',
    'rr': 'Wolt',
    'si': 'Cita Previa',
    'ss': 'Hezzl',
    'th': 'WestStein',
    'pf': 'pof.com',
    'py': 'Monese',
    'qe': 'GG',
    'fj': 'Potato Chat',
    'sq': 'KuCoinPlay',
    'co': 'Rediffmail',
    'tl': 'Truecaller',
    'qu': 'Agroinform',
    'lr': 'Okta',
    'px': 'Nifty',
    'dx': 'Powerkredite',
    'ib': 'Immowelt',
    'uz': 'OffGamers',
    'gd': 'Surveytime',
    'cc': 'Quipp',
    'le': 'E bike Gewinnspiel',
    'rd': 'Lenta',
    'we': 'ДругВокруг',
    'cd': 'SpotHit',
    'pp': 'Huya',
    'dh': 'eBay',
    'lw': 'MrGreen',
    'hu': 'Ukrnet',
    'qa': 'MyFishka',
    'yo': 'Amasia',
    'me': 'Line messenger',
    'il': 'IQOS',
    'zf': 'OnTaxi',
    'zh': 'Zoho',
    'iz': 'Global24',
    're': 'Coinbase',
    'ey': 'miloan',
    'ri': 'BillMill',
    'kp': 'HQ Trivia',
    'vo': 'Brand20ua',
    'zy': 'Nttgame',
    'ji': 'Monobank',
    'wg': 'Skout',
    'gp': 'Ticketmaster',
    'cp': 'Uklon',
    'tn': 'LinkedIN',
    'sn': 'OLX',
    'st': 'Auchan',
    'rz': 'EasyPay',
    'gi': 'Hotline',
    'la': 'ssoidnet',
    'zz': 'Dent',
    'gl': 'GlobalTel',
    'cm': 'Prom',
    'de': 'Karusel',
    'df': 'Happn',
    'ya_1': 'Яндекс + переад.',
    'tw': 'Twitter',
    'tx': 'Bolt',
    'ls': 'Careem',
    'ya': 'Яндекс',
    'av_1': 'Авито + переад.',
    'ua': 'BlaBlaCar',
    'dp': 'ProtonMail',
    'yf': 'Citymobil',
    'ub': 'Uber',
    'hw': 'AliPay',
    'ds': 'Discord',
    'dt': 'Delivery Club',
    'yk': 'СпортМастер',
    'yl': 'Yalla',
    'ma': 'Mail.ru',
    'ym': 'Юла',
    'mb': 'Yahoo',
    'uk': 'Airbnb',
    'qi': '32red',
    'mg': 'Магнит',
    'yw': 'Grindr',
    'ig': 'Instagram',
    'uu': 'Wildberries',
    'qq': 'Tencent QQ',
    'mm': 'Microsoft',
    'ab': 'Alibaba',
    'qr': 'MEGA',
    'im': 'Imo',
    'qw': ' Qiwi',
    'za': 'JDcom',
    'mt': 'Steam',
    'am': 'Amazon',
    'an': 'Adidas',
    'et': 'Clubhouse',
    'ew': 'Nike',
    'vi': 'Viber',
    'fx_1': 'PGbonus+переад',
    'av': 'Avito',
    'vk': 'Vkontakte',
    'nf': 'Netflix',
    'rl': 'inDriver',
    'fb': 'facebook',
    'fd': 'Mamba',
    'jj': 'Aitu',
    'bd': 'Пятерочка',
    'ry': 'McDonalds',
    'jr': 'Самокат',
    'nv': 'Naver',
    'bl': 'BIGO LIVE',
    'wa': 'Вацап',
    'wb': 'WeChat',
    'nz': 'Foodpanda',
    'wf': 'YandexGo',
    'fu': 'Snapchat',
    'fx': 'PGbonus',
    'sg': 'OZON',
    'bz': 'Blizzard',
    'oi': 'Tinder',
    'gb': 'YouStar',
    'ok': 'Одноклассники',
    'wx': 'Apple',
    'ot_1': 'Любой другой + переад',
    'ot': 'Любой другой',
    'go': 'youtube,Gmail',
    'kt': 'KakaoTalk',
    'gt': 'Gett',
    'xk': 'DiDi',
    'tg': 'Telegram',
    'cy': 'РСА',
    'tk': 'МВидео',
    'xr': 'Tango',
    'lf': 'TikTok',
    'pl': 'Tango',
    'da': 'MTS CashBack',
    'pm': 'AOL',
    'ym_1': 'Юла + переад',
    'ts': 'PayPal',
    'po': 'premium.one',
}
